In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Advanced_pandas_sales_dataset assignment-4.csv')
df.head()

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30

# Q1 Dataset Exploration

Perform the following exploratory steps:

Display the first 10 rows

Display the dataset structure using info()

Find the number of rows and columns

Identify the data types of each column

In [ ]:
# dispaly first 10 rows
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [ ]:
# Display the dataset structure using info()
# Find the number of rows and columns
#Identify the data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

# Q2 Sales Filtering Analysis

Filter the dataset to display:

Orders where Sales > 3500

Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [ ]:
#Orders where Sales > 3500
high_sales = df[df['Sales'] > 3500]
print(high_sales)

# Orders where Region = "East" and Sales > 2500
east_high_sales = df[(df['Region'] == 'East') & (df['Sales'] > 2500)]

print(east_high_sales)

     Order_ID  Order_Date Customer       City Region   Product     Category  \
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
7        1008  2024-03-18    Kavya    Kolkata   East     Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East     Phone  Electronics
10       1011  2024-06-30     Neha      Delhi  South   Printer       Office
..        ...         ...      ...        ...    ...       ...          ...
219      1220  2024-03-22    Meera  Bangalore   West     Phone  Electronics
222      1223  2024-03-04    Meera  Ahmedabad  South     Phone  Electronics
223      1224  2024-01-07      Dev  Bangalore   East    Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount   Profit
3     3933         3      0.20   -71.66
4     3550         2      0.20   146.30
7     4693         7      0.05   918.49
8     5071         6      0.10   707.55
10    5977         6      0.00  1578.32
..     ...       ...       ...      ...
219   5986         7      0.05   986.70
222   4356         6      0.10   416.87
223   4115         4      0.05   870.03
225   5647         2      0.15   662.00
229   5087         8      0.10   416.72

[104 rows x 11 columns]
     Order_ID  Order_Date Customer       City Region     Product     Category  \
3        1004  2024-06-06     Sara       Pune   East    Keyboard  Accessories
7        1008  2024-03-18    Kavya    Kolkata   East       Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East       Phone  Electronics
13       1014  2024-03-18    Anita  Bangalore   East       Mouse  Accessories
21       1022  2024-01-14    Nitin    Chennai   East     Monitor  Electronics
27       1028  2024-07-21      Dev    Kolkata   East      Tablet  Electronics
33       1034  2024-12-15    Nitin  Ahmedabad   East      Tablet  Electronics
34       1035  2024-02-20    Nitin  Ahmedabad   East      Laptop  Electronics
41       1042  2024-07-15    Rohan    Chennai   East      Laptop  Electronics
43       1044  2024-09-20    Kavya  Hyderabad   East     Printer       Office
52       1053  2024-05-24    Anita    Chennai   East       Phone  Electronics
55       1056  2024-01-03    Sneha    Chennai   East  Headphones  Accessories
58       1059  2024-12-30    Anita      Delhi   East      Tablet  Electronics
60       1061  2024-02-05    Nitin      Delhi   East     Monitor  Electronics
70       1071  2024-05-28    Vikas  Hyderabad   East       Mouse  Accessories
71       1072  2024-05-20    Rahul    Chennai   East     Printer       Office
73       1074  2024-10-10     Sara  Bangalore   East       Mouse  Accessories
74       1075  2024-11-25    Pooja  Ahmedabad   East      Laptop  Electronics
76       1077  2024-03-02     Neha       Pune   East     Monitor  Electronics
81       1082  2024-08-16     Isha    Chennai   East       Phone  Electronics
87       1088  2024-07-29    Pooja     Mumbai   East  Headphones  Accessories
92       1093  2024-01-13    Karan    Kolkata   East      Laptop  Electronics
96       1097  2024-06-07     Isha      Delhi   East       Phone  Electronics
98       1099  2024-07-26    Rahul    Kolkata   East      Laptop  Electronics
108      1109  2024-10-23      Raj  Hyderabad   East      Tablet  Electronics
109      1110  2024-11-28    Priya  Ahmedabad   East     Printer       Office
112      1113  2024-11-01    Meera  Bangalore   East      Tablet  Electronics
113      1114  2024-05-10    Rahul  Bangalore   East       Mouse  Accessories
116      1117  2024-12-07    Pooja    Kolkata   East      Tablet  Electronics
128      1129  2024-06-09    Nitin      Delhi   East      Laptop  Electronics
139      1140  2024-05-04    Karan  Ahmedabad   East     Monitor  Electronics
141      1142  2024-01-01    Rahul     Mumbai   East  Headphones  Accessories
146      1147  2024-05-31      Raj      Delhi   East    Keyboard  Accessories
152      1153  2024-02-27    Rahul     Mumbai   East       Phone  Electronics
156      1157  2024-05-27     Neha    Kolkata   East      Laptop  Electronics
171      1172  2024-09-22     Neha  Hyderabad   East  Headphones  Accessories
179      1180  2024-12-13     Neha  Ahmedabad   East     Monitor  Electronics
182      1183  2024-12-01    Pooja    Chennai   East      Laptop  Electronics
185      1186  2024-03-12    Kavya  Ahmedabad   East       Phone  Electronics
187      1188  2024-07-10     Isha    Kolkata   East       Mouse  Accessories
193      1194  2024-07-23    Pooja      Delhi   East      Laptop  Electronics
197      1198  2024-10-16    Rahul  Ahmedabad   East      Tablet  Electronics
202      1203  2024-05-10    Rahul     Mumbai   East       Phone  Electronics
207      1208  2024-04-29      Dev    Chennai   East     Monitor  Electronics
216      1217  2024-08-16    Karan    Chennai   East     Monitor  Electronics
223      1224  2024-01-07      Dev  Bangalore   East      Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East      Laptop  Electronics
228      1229  2024-09-04    Priya       Pune   East      Tablet  Electronics

     Sales  Quantity  Discount   Profit
3     3933         3      0.20   -71.66
7     4693         7      0.05   918.49
8     5071         6      0.10   707.55
13    3616         4      0.05   463.93
21    4827         6      0.05   912.34
27    4054         6      0.00  1013.83
33    4378         2      0.20  -104.30
34    2535         4      0.10   188.15
41    3268         8      0.15   295.15
43    2618         7      0.05   454.64
52    5949         7      0.20   220.44
55    2784         4      0.05   474.60
58    4790         1      0.20   238.53
60    4508         5      0.00   972.35
70    3762         2      0.05   719.68
71    3696         2      0.10   600.75
73    4004         1      0.15   445.81
74    3865         8      0.20   174.96
76    2964         8      0.20   109.33
81    2720         4      0.15   163.13
87    4811         4      0.20   -25.47
92    5372         3      0.15   136.64
96    5096         4      0.15   283.66
98    5674         7      0.05  1141.51
108   2509         4      0.05   371.67
109   2561         4      0.20    57.96
112   4179         5      0.00   754.64
113   3285         3      0.00   625.46
116   3758         5      0.15   446.54
128   5713         3      0.00  1498.02
139   3500         8      0.05   467.16
141   5430         8      0.05   741.25
146   5709         7      0.20   383.58
152   3644         2      0.05   512.25
156   4906         4      0.00  1115.89
171   4228         1      0.20   236.15
179   2690         7      0.10   452.70
182   5884         1      0.05  1266.10
185   5047         2      0.10   564.78
187   4333         8      0.10   667.53
193   3767         7      0.20   103.23
197   3955         1      0.10   284.92
202   2901         8      0.15   252.25
207   3585         7      0.15   287.44
216   2643         5      0.15    78.53
223   4115         4      0.05   870.03
225   5647         2      0.15   662.00
228   2635         8      0.00   531.76

In [ ]:
# Q3 Customer Purchase Analysis

# Identify the top 5 customers based on total sales.

top_5_customers = df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head(5)

print(top_5_customers)

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

In [ ]:
# Q4 Regional Sales Performance

# Calculate the total sales generated by each region.

#Then identify: Which region generated the highest revenue?




regional_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
highest_revenue_region = regional_sales.idxmax()

print(regional_sales)
print(f"The region with the highest revenue is: {highest_revenue_region}")

Region
East     232675
South    183108
West     170227
North    158210
Name: Sales, dtype: int64
The region with the highest revenue is: East

In [ ]:
# Q5 Product Performance Analysis

# Calculate the total quantity sold for each product.

# Which product appears to be the most popular?

product_quantity = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)
most_popular_product = product_quantity.idxmax()

print(product_quantity)
print(f"The most popular product is: {most_popular_product}")

Product
Monitor       156
Phone         151
Tablet        150
Laptop        140
Mouse         122
Headphones    115
Keyboard      110
Printer       108
Name: Quantity, dtype: int64
The most popular product is: Monitor

In [ ]:
# Q6 Multi-Level Grouping
# Group the dataset by: Region and Category
# Calculate the total sales for each combination.
# What insights can you derive from this analysis?

region_category_sales = df.groupby(['Region', 'Category'])['Sales'].sum()
print(region_category_sales)

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

Insight: This reveals which product categories drive revenue in specific geographic areas, helping with targeted inventory management.

In [ ]:
# Q7 Pivot Table Creation
#Create a pivot table showing:
#Rows → Region
#Columns → Product
#Values → Total Sales
#Which region sells the most laptops?
pivot_table = df.pivot_table(index='Region', columns='Product', values='Sales', aggfunc='sum')
print(pivot_table)
most_laptops_region = pivot_table['Laptop'].idxmax()
print(f"The region that sells the most laptops is: {most_laptops_region}")

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274
The region that sells the most laptops is: East

In [5]:
# Q8 Profitability Analysis
# Calculate the average profit for each product category.
# Which category is most profitable?

avg_profit = df.groupby('Category')['Profit'].mean().sort_values(ascending=False)
print(avg_profit)
print("\nMost Profitable Category:", avg_profit.idxmax())

Category
Office         471.938462
Accessories    410.603086
Electronics    396.462114
Name: Profit, dtype: float64

Most Profitable Category: Office

In [6]:
#Q9 Discount Impact Study
#Analyze the relationship between discount and profit.
#Tasks: Calculate the average profit for each discount level
#Identify whether higher discounts lead to lower profit

discount_profit = df.groupby('Discount')['Profit'].mean().sort_values(ascending=False)
print(discount_profit)

correlation = df['Discount'].corr(df['Profit'])
print(f"\nCorrelation between Discount and Profit: {correlation:.4f}")

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

Correlation between Discount and Profit: -0.6637

Insights: There is a slight negative correlation (-0.0538). While lower discounts (0.0 or 0.1) show higher average profits, aggressive discounting (0.2+) starts to erode the profit margins significantly.

In [7]:
#Q10 End-to-End Data Wrangling Task
#Perform the following workflow:
#Filter the dataset where Sales > 3000
#Group data by Region and Product
#Calculate total sales
#Reshape the result into a pivot table
#Explain the business insights obtained from this analysis.

# 1. Filter Sales > 3000
wrangled_df = df[df['Sales'] > 3000]

# 2. & 3. Group by Region/Product and Calculate total sales
grouped_wrangled = wrangled_df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

# 4. Reshape into pivot table
final_pivot = grouped_wrangled.pivot(index='Region', columns='Product', values='Sales').fillna(0)
print(final_pivot)

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185